// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // O CLI (migrate/introspect) usa a conexao DIRETA (sem pooler) - e o que
  // o Supabase/Neon recomendam pra DDL. O app em runtime usa DATABASE_URL
  // (com pooler) via driver adapter em src/lib/prisma.ts, separadamente.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
